### PR TITLE
feat: Update service feature

### PR DESCRIPTION
**Pull request by mohandast52**
## Proposed changes

- feature to update the "Service"

### demo below 👇 

- Created a new service (id: 27) for illustration and successfully updated the agentID to 2 as expected.
- The previous functionality of updating for EVM should function the same as well.

https://github.com/valory-xyz/autonolas-registry-frontend/assets/22061815/b7fdb0aa-a901-427b-9ab5-020abebd8c8d

## Types of changes

What types of changes does your code introduce to `autonolas-registry-frontend`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] My pull request is targeted against the main branch (left side), and I've started my branch from our main.
- [ ] I've ensured that linting and unit tests pass locally with my changes, and CI also passes successfully.
- [ ] I've included tests to validate the effectiveness of my fix or to demonstrate that my feature functions correctly.
- [ ] I've verified that my changes do not reduce code coverage.
- [x] I've added any necessary documentation as needed.
- [x] I've confirmed that any dependent changes have been merged and published in downstream modules.
- [ ] If the onload page involves contract interaction, I've ensured it is client-side rendered using next/dynamic.
- [ ] I've updated next.config.js header to include the new URL for secure app interaction

### CODE REVIEW

**Review by kupermind — APPROVED** [review]

**Comment by oaksprout** [comment]
@mohandast52 

image
Could we already enable this?

image
The form should already be pre-filled with the existing state. Otherwise it's much too big of a UX hurdle – can lead to big errors.

Also, even though the Owner Address input is disabled, the Prefill Address button is still visible. The button should be hidden if the input is disabled.

https://github.com/valory-xyz/autonolas-registry-frontend/assets/66292936/ad825839-eaaa-466f-85f0-6fb222d8aa82
Not sure if related to this PR, but on devent My Services, only 10 services are showing, but this address has more than 20 minted to it.

image
Why is Update present on My Services action column, but not on Services? Should be a pretty simple conditional, no?


https://valory-workspace.slack.com/files/U044UPWNZ5L/F06EASBLL9M/solana-update-submit_copy.mov
The update form doesn't actually work for me – I don't get an error or any information about why not.

**Comment by oaksprout** [comment]
image

The third issue above is still present @mohandast52 – on devnet I have minted more than 10 services, but only 10 are visible.

**Comment by oaksprout** [comment]
@mohandast52 – service is still not updating – no Phantom model is being triggered.

https://valory-workspace.slack.com/files/U044UPWNZ5L/F06FR49JTR7/solana-update-no-trigger.mov

The console mentions something related to chainId, so maybe there's some interference with EVM wallet? Or maybe it's related to how my service was created?

image

**Comment by oaksprout** [comment]
Again, from a usability point of view, if the Owner Address input isn't editable, the Prefill Address link should also be disabled.

image

**Comment by oaksprout** [comment]
OK, seems to be working again for me now. Maybe was related to the devnet issues? Either way, lgtm.

**Review by oaksprout — DISMISSED** [review]

**Review by oaksprout — APPROVED** [review]

**Review by kupermind — APPROVED** [review]

**Pull request merged**
